In [33]:
import pandas as pd
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from decimal import *

In [34]:
Datos = pd.read_csv('NUEVOSDATAAUTOS.csv')
Datos.head(745)

,Model,Variant,Manufacturer,Type,Gamma,Category_CC,TotalRob,Umbral,%Umbral
0,147,All,Alfa Romeo,B: SMALL SALOONS,baja,3200cc-4800cc,91,"0,003202509885682","0,32"
1,33& 145& 146& 1750& Arna,All,Alfa Romeo,B: SMALL SALOONS,baja,1500cc – 2000cc,72,"0,003202509885682","0,32"
2,75& 2000& Alfetta& Giulietta,All,Alfa Romeo,C: MEDIUM SALOONS,alta,2000cc-2500cc,8,"0,003202509885682","0,32"
3,155& 156,All,Alfa Romeo,C: MEDIUM SALOONS,ata,2500cc-3200cc,298,"0,003202509885682","0,32"
4,GT,All,Alfa Romeo,C: MEDIUM SALOONS,alta,1500cc – 2000cc,10,"0,003202509885682","0,32"
...,...,...,...,...,...,...,...,...,...
739,S60,All,Volvo,D: LARGE SALOONS,baja,2000cc-2500cc,129,"0,013526720158772","1,35"
740,S80,All,Volvo,D: LARGE SALOONS,baja,2500cc-3200cc,98,"0,013526720158772","1,35"
741,V50,All,Volvo,D: LARGE SALOONS,baja,1500cc – 2000cc,0,"0,013526720158772","1,35"
742,XC70,All,Volvo,E: LUXURY SALOONS,alta,1500cc – 2000cc,8,"0,013526720158772","1,35"
743,XC90,All,Volvo,G: 4x4 & PEOPLE CARRIER,ata,1500cc – 2000cc,82,"0,013526720158772","1,35"

In [35]:
#Recibe el Umbral y el porcentaje elegido por el profesor
def llenar(umbral, porcentaje):
    value = umbral.split(',')
    if(len(value)==2):      
        num = value[0]+'.'+value[1]
    else:
        num = value[0]+'.0'
    if(float(num)>=float(porcentaje)):
        return 'SI'
    else:
        return 'NO'

Datos['VenderSeguro'] = Datos.apply(lambda row: llenar(str(row['%Umbral']), 5), axis=1)
Datos.head()

,Model,Variant,Manufacturer,Type,Gamma,Category_CC,TotalRob,Umbral,%Umbral,VenderSeguro
0,147,All,Alfa Romeo,B: SMALL SALOONS,baja,3200cc-4800cc,91,"0,003202509885682","0,32",NO
1,33& 145& 146& 1750& Arna,All,Alfa Romeo,B: SMALL SALOONS,baja,1500cc – 2000cc,72,"0,003202509885682","0,32",NO
2,75& 2000& Alfetta& Giulietta,All,Alfa Romeo,C: MEDIUM SALOONS,alta,2000cc-2500cc,8,"0,003202509885682","0,32",NO
3,155& 156,All,Alfa Romeo,C: MEDIUM SALOONS,ata,2500cc-3200cc,298,"0,003202509885682","0,32",NO
4,GT,All,Alfa Romeo,C: MEDIUM SALOONS,alta,1500cc – 2000cc,10,"0,003202509885682","0,32",NO

In [36]:
features_train = Datos.iloc[0:743,2:6]
target_train = Datos.iloc[0:743,9]

In [37]:
le = preprocessing.LabelEncoder()
f0 = le.fit_transform(features_train.iloc[0:743,0])
f1 = le.fit_transform(features_train.iloc[0:743,1])
f2 = le.fit_transform(features_train.iloc[0:743,2])
f3 = le.fit_transform(features_train.iloc[0:743,3])
label = le.fit_transform(target_train)
features = list(zip(f0,f1,f2,f3))
#print(target_train)
#print(features_train)
#print(label)
#print(features)

In [38]:
model1 = GaussianNB()
model1.fit(features, label)
Predicted = model1.predict([[0,1,2,3]])
print(Predicted)
# 0 es no se debe vender seguro
# 1 si se debe vender

[0]